# Generated by Django 3.2.21 on 2023-09-19 05:16

import back.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=back.models.CustomPhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
